name: Feature Request
description: Suggest a new feature or enhancement for CodeMate
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!

  - type: textarea
    id: description
    attributes:
      label: What would you like to see?
      description: Describe the feature and why it would be useful
      placeholder: |
        I would like CodeMate to support...
        This would help me because...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: How should it work?
      description: Describe how you envision this feature working
      placeholder: When I run... it should...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context (optional)
      description: Add any other context, alternatives considered, or examples
      placeholder: Any additional information...
