name: Spec
description: Track a feature spec managed by the pm plugin
title: "[Spec]: "
labels: ["spec"]
body:
  - type: markdown
    attributes:
      value: |
        This issue tracks a feature spec. It is managed automatically by the `/pm:spec-*` skills.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this spec solve and why does it matter?
      placeholder: |
        Users currently have to... which causes...
        This spec addresses that by...
    validations:
      required: true

  - type: textarea
    id: goals
    attributes:
      label: Goals & Success Criteria
      description: What does done look like? List measurable outcomes.
      placeholder: |
        - Users can...
        - System handles...
    validations:
      required: true

  - type: textarea
    id: requirements
    attributes:
      label: Functional Requirements
      description: What must the feature do?
      placeholder: |
        - Requirement 1
        - Requirement 2

  - type: textarea
    id: out_of_scope
    attributes:
      label: Out of Scope
      description: What is explicitly excluded from this spec?
      placeholder: |
        - Not included: ...

  - type: textarea
    id: context
    attributes:
      label: Additional Context (optional)
      description: Links, constraints, dependencies, or other relevant information
