name: Task
description: Implementation task linked to a spec
title: "[Task]: "
labels: ["task"]
body:
  - type: markdown
    attributes:
      value: |
        Tasks are normally created automatically by `/pm:spec-decompose`. Use this template only for manual task creation.

  - type: input
    id: spec-ref
    attributes:
      label: Parent Spec
      description: Link to the parent spec issue (e.g. #42)
      placeholder: "#42"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be done?
    validations:
      required: true

  - type: input
    id: tags
    attributes:
      label: Tags
      description: Area tags (e.g. api, ui, data, infra)
      placeholder: api, data

  - type: input
    id: estimate
    attributes:
      label: Effort Estimate
      placeholder: 1d

  - type: input
    id: depends-on
    attributes:
      label: Depends On
      description: Task issue numbers this depends on
      placeholder: "#10, #11"

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: true
